#!/usr/bin/env python
# coding: utf-8

# In[2]:


from timeit import Timer


# List测试：l = l + [i]

# In[3]:


def test1():
    l = []
    for i in range(1000):
        l = l + [i]


# In[6]:


t1 = Timer("test1()", "from __main__ import test1")
print("concat ",t1.timeit(number=1000), "seconds")


# In[9]:


def test2():
    l = []
    for i in range(1000):
        l.append(i)


# In[12]:


t2 = Timer("test2()", "from __main__ import test2")
print("append ",t2.timeit(number=1000), "seconds")


# In[13]:


def test3():
    l = [i for i in range(1000)]


# In[14]:


t3 = Timer("test3()", "from __main__ import test3")
print("comprehension ",t3.timeit(number=1000), "seconds")


# In[15]:


def test4():
    l = list(range(1000))


# In[16]:


t4 = Timer("test4()", "from __main__ import test4")
print("list range ",t4.timeit(number=1000), "seconds")


# POP测试

# In[10]:


x = [i for i in range(2000000)]


# In[11]:


# x = range(2000000)
pop_zero = Timer("x.pop(0)","from __main__ import x")
print("pop_zero ",pop_zero.timeit(number=1000), "seconds")


# In[12]:


pop_end = Timer("x.pop()","from __main__ import x")
print("pop_end ",pop_end.timeit(number=1000), "seconds")

