#!/usr/bin/env python
# coding: utf-8

# In[1]:


#List（列表）
    #列表可以完成大多数集合类的数据结构实现。
    #列表中元素的类型可以不相同，它支持数字，字符串甚至可以包含列表（所谓嵌套）。
    #列表是写在方括号([])之间、用逗号分隔开的元素列表。
    #和字符串一样，列表同样可以被索引和截取，列表被截取后返回一个包含所需元素的新列表。
    #列表同样可以被索引和截取,索引值以 0 为开始值，-1 为从末尾的开始位置。
list = ['abc',123,2.34,'shuyun',70.2]
tinylist=[123,'shuyun']
print(list)
print(list[0])
print(list[1:3])
print(list[2:])
print(tinylist*2)
print(list+tinylist)


# In[7]:


l2 = [i for i in range(2000)]
# l2
l2[0:3]


# In[4]:


list.append("test1")
print(list.pop())
list.insert(0,"test2")


# In[5]:


#与Python字符串不一样的是，列表中的元素是可以改变的
a=[1,2,3,'a','b','c']
a[0]=9
a[2:5]=[13,14,15]
print(a)
a[2:5]=[]
a


# In[ ]:




